version: '3.3'

networks:
  traefik-net:
    external: false

services:
  netflix-eureka-naming-server:
    image: pmr2791/pmr2798791:netflix-eureka-naming-server
    networks:
      - traefik-net
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.frontend.rule=Host:netflix-eureka-naming-server"
      - traefik.port=5000
      - traefik.enable=true
      - traefik.docker.network=traefik-net	  
  spring_cloud_server:
    image: pmr2791/pmr2798791:spring_cloud_server
    networks:
      - traefik-net
    ports:
      - "8888:8888"
    depends_on:
      - netflix-eureka-naming-server 
    environment:
      - REGISTRY_HOST=netflix-eureka-naming-server
      - SERVER_PORT=8888
      - FEIGN_CLIENT_CONFIG_DEFAULT_CONNECTTIMEOUT=160000000
      - FEIGN_CLIENT_CONFIG_DEFAULT_READTIMEOUT=160000000
      - RIBBON_READTIMEOUT=160000000
      - RIBBON_CONNECTTIMEOUT=160000000
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.frontend.rule=Host:spring_cloud_server"	  
      - traefik.port=5000
      - traefik.enable=true
      - traefik.docker.network=traefik-net	  
  limits-server:
    image: pmr2791/pmr2798791:limits-server
    networks:
      - traefik-net
    ports:
      - "8889:8889"
    depends_on:
      - netflix-eureka-naming-server 
    environment:
      - CLOUD_HOST=spring_cloud_server
      - REGISTRY_HOST=netflix-eureka-naming-server
      - SERVER_PORT=8889
      - FEIGN_CLIENT_CONFIG_DEFAULT_CONNECTTIMEOUT=160000000
      - FEIGN_CLIENT_CONFIG_DEFAULT_READTIMEOUT=160000000
      - RIBBON_READTIMEOUT=160000000
      - RIBBON_CONNECTTIMEOUT=160000000
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.frontend.rule=Host:limits-server"	  
      - traefik.port=5000
      - traefik.enable=true
      - traefik.docker.network=traefik-net	  
  netflix-zuul-api-gateway-server:
    image: pmr2791/pmr2798791:netflix-zuul-api-gateway-server
    networks:
      - traefik-net
    ports:
      - "8765:8765"
    depends_on:
      - netflix-eureka-naming-server 
    environment:
      - REGISTRY_HOST=netflix-eureka-naming-server
      - SERVER_PORT=8765
      - FEIGN_CLIENT_CONFIG_DEFAULT_CONNECTTIMEOUT=160000000
      - FEIGN_CLIENT_CONFIG_DEFAULT_READTIMEOUT=160000000
      - RIBBON_READTIMEOUT=160000000
      - RIBBON_CONNECTTIMEOUT=160000000
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.frontend.rule=Host:netflix-zuul-api-gateway-server"	  
      - traefik.port=5000
      - traefik.enable=true
      - traefik.docker.network=traefik-net	  
  currency-conversion-service:
    image: pmr2791/pmr2798791:currency-conversion-service
    networks:
      - traefik-net
    ports:
      - "8100:8100"
    depends_on:
      - netflix-eureka-naming-server 
    environment:
      - REGISTRY_HOST=netflix-eureka-naming-server
      - SERVER_PORT=8100
      - FEIGN_CLIENT_CONFIG_DEFAULT_CONNECTTIMEOUT=160000000
      - FEIGN_CLIENT_CONFIG_DEFAULT_READTIMEOUT=160000000
      - RIBBON_READTIMEOUT=160000000
      - RIBBON_CONNECTTIMEOUT=160000000
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.frontend.rule=Host:currency-conversion-service"	  
      - traefik.port=5000
      - traefik.enable=true
      - traefik.docker.network=traefik-net	  
        
  currency-exchange-service:
    image: pmr2791/pmr2798791:currency-exchange-service
    networks:
      - traefik-net
    ports:
      - "8001:8001"
    depends_on:
      - netflix-eureka-naming-server 
    environment:
      - REGISTRY_HOST=netflix-eureka-naming-server
      - SERVER_PORT=8001
      - FEIGN_CLIENT_CONFIG_DEFAULT_CONNECTTIMEOUT=160000000
      - FEIGN_CLIENT_CONFIG_DEFAULT_READTIMEOUT=160000000
      - RIBBON_READTIMEOUT=160000000
      - RIBBON_CONNECTTIMEOUT=160000000
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.frontend.rule=Host:currency-exchange-service"	  
      - traefik.port=5000
      - traefik.enable=true
      - traefik.docker.network=traefik-net	  
